### ISSUE TITLE
No such option --group-id when run ocrd workspace add

### ISSUE THREAD

**Issue by nv-quan** [OCR-D/ocr-d.github.io#21]
Hello,
I'm following the Cookbook but I couldn't run ocrd workspace add with option --group-id. Is this deprecated or a typo?
https://github.com/OCR-D/ocr-d.github.io/blob/8a7d0b1fcf108d68bdbe3e8f0f4870d81a828a7e/en/cookbook.html#L257
Thank you.

**Comment by VolkerHartmann** [comment]
OOOPS, you are right.
This is no longer valid.
Please use ‘ocrd workspace add –help’ to get the right options.
You have to use ‘-G’ or ‘—file-grp’ instead.

Von: Quan Nguyen <notifications@github.com>
Gesendet: Dienstag, 17. März 2020 09:01
An: OCR-D/ocr-d.github.io <ocr-d.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [OCR-D/ocr-d.github.io] No such option --group-id when run ocrd workspace add (#21)


Hello,
I'm following the Cookbook but I couldn't run ocrd workspace add with option --group-id. Is this deprecated or a typo?
https://github.com/OCR-D/ocr-d.github.io/blob/8a7d0b1fcf108d68bdbe3e8f0f4870d81a828a7e/en/cookbook.html#L257
Thank you.

**Comment by nv-quan** [comment]
Thank you for your fast response. Besides, I think this is also a typo:
https://github.com/OCR-D/ocr-d.github.io/blob/8a7d0b1fcf108d68bdbe3e8f0f4870d81a828a7e/en/cookbook.html#L236

**Comment by kba** [comment]
We should delete the cookbook, it's outdated and there is better documentation linked at https://ocr-d.de/en/use.html.

**Comment by bertsky** [comment]
> We should delete the cookbook, it's outdated and there is better documentation linked at https://ocr-d.de/en/use.html.

@kba so you want to replace the outdated cookbook in favour of the others under use.html / docs? Can you please comment in the related discussion [here](https://github.com/OCR-D/ocrd_all/pull/74#issuecomment-604534229)?
